### PR TITLE
Switch to .NET 4(.5)

### PR DESCRIPTION
**Pull request by kika123**
For more modern support and Windows on ARM processors. This pull request enables an IceChat build to run unmodified on RT 8.1(tested with a compile done on my RT 8.1 device, as I have MSBuild there)

### CODE REVIEW

**Comment by icechat** [comment]
There is currently an IceChat9-45-VS2015.sln solution to open IceChat in VS 2015 and it is built with .Net 4.5 , so this is already implemented.

**Comment by kika123** [comment]
The manifest isn't right when using IceChat9-45-VS2015, my patch makes it usable

**Comment by kika123** [comment]
(try to run the result on Windows on ARM or ARM64, for example)
That's why I adapted the manifest

**Comment by icechat** [comment]
Understandable, the fix will gt applied.
Thanks

**Pull request closed without merging**
